// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Obter valores das variáveis de ambiente
const ENV_URL = import.meta.env.VITE_SUPABASE_URL;
const ENV_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

// Função para validar se as variáveis são reais (não placeholder)
const isValidConfig = (url?: string, key?: string): boolean => {
  if (!url || !key) return false;
  
  // Verificar se não são valores de placeholder/demo
  const isPlaceholderUrl = url.includes('rilcjsdbxlyfvuqyqfed') || url.includes('demo');
  const isPlaceholderKey = key.includes('supabase-demo') || key.length < 100;
  
  return !isPlaceholderUrl && !isPlaceholderKey;
};

// Verificar se as variáveis estão realmente configuradas
const hasValidConfig = isValidConfig(ENV_URL, ENV_KEY);

// Configuração final
const SUPABASE_URL = hasValidConfig ? ENV_URL! : 'https://rilcjsdbxlyfvuqyqfed.supabase.co';
const SUPABASE_ANON_KEY = hasValidConfig ? ENV_KEY! : 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0';

// Criar cliente Supabase
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY);

// Status da configuração
export const isUsingPlaceholderConfig = !hasValidConfig;
export const isSupabaseConfigured = () => hasValidConfig;

// Exportar configurações
export { SUPABASE_URL, SUPABASE_ANON_KEY as SUPABASE_PUBLISHABLE_KEY };

// Debug em desenvolvimento
if (typeof window !== 'undefined' && import.meta.env.DEV) {
  console.log('🔧 Supabase Config Status:', {
    configured: hasValidConfig,
    hasUrl: !!ENV_URL,
    hasKey: !!ENV_KEY,
    urlPreview: ENV_URL ? `${ENV_URL.substring(0, 20)}...` : 'não configurada'
  });
}
